services:
    crisis_text_line.replica_route_limiter.controller.listener:
        class: CrisisTextLine\ReadReplicaRouteLimiterBundle\EventListener\ControllerListener
        arguments: ["@crisis_text_line.replica_route_limiter.util.config", "@database_connection"]
        tags:
            - { name: kernel.event_subscriber }

    crisis_text_line.replica_route_limiter.util.config:
        class: CrisisTextLine\ReadReplicaRouteLimiterBundle\Util\Configurations
        arguments: ["@annotation_reader"]
        shared: false
