language: php

php:
    - 7.2
    - 7.3
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit --testdox
