language: php

php:
    - 5.6
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit --test-dox
